sefaz:
   truststore:
     path: C:\Users\nicho\Downloads\server-keystore.jks
     password: server-keystore-p455w0rd
   docfe:
     conhecimento:
      url: https://www1.cte.fazenda.gov.br/CTeDistribuicaoDFe/CTeDistribuicaoDFe.asmx
     
  