spring:  profiles:    active:    - dev

---
spring:  config:    activate:      on-profile:      - dev  datasource:    url: jdbc:mysql://localhost:3306/fretecloud?useTimezone=true&serverTimezone=UTC
    username: root
    password: Vicinitech12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    hibernate:      ddl-auto: update    
sefaz:
   truststore:
     path: C:\Users\nicho\Downloads\server-keystore.jks
     password: server-keystore-p455w0rd
   DFe:
     conhecimento:
      url: https://www1.cte.fazenda.gov.br/CTeDistribuicaoDFe/CTeDistribuicaoDFe.asmx
      soapAction: http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe/cteDistDFeInteresse
 
  